Выполнение задания, часть1
Rzr18/arhitecture-sprint-3 pull request #1
Opened 2024-12-14 16:37 UTC by Rzr18

2024-12-21 14:07 UTC, dchekushin requested changes

2024-12-21 14:07 UTC, dchekushin commented on Project_template_part_1.md
> +[Диаграмма контекста AsIs](https://www.plantuml.com/plantuml/png/VL7DRjD04BxxAHQVWYZrXHEdIW6fGe2Y1ixLrbabbhoxrdeSoeqwGXoAr0jdaE05sWghRfiwhp3xHimu5J4uwi7QdTdlP-RpNWxIGQ7J0198bHXhAiM-rKeChG5r3E958gTEwY
- Выдели мобильное приложение / веб-сайт отдельным контейнером. Именно с ними взаимодействует пользователь.
- Укажи протоколы, технологии взаимодействия, например http, между контейнерами.

2024-12-21 14:07 UTC, dchekushin commented on Project_template_part_1.md
Продумай в дополнение, следующие домены:  "Телеметрия",  "Пользовательские сценарии" и "Управление домом"

2024-12-21 14:07 UTC, dchekushin commented on С4/microservices-containers.puml
> +    SystemQueue(Queue, "Kafka Queue", "Очередь сообщений. Pub/Sub model")
Чем обусловлено взаимодействие API Gateway со всеми микросервисами через очередь? Выглядит избыточно.

2024-12-21 14:07 UTC, dchekushin commented on С4/microservices-erd.puml
> +    + type_id
Для устройств стоит добавить атрибут статуса (Включено / выключено). По мере развития системы, могут добавится устройства с дополнительными рабочими режимами и соответственно статусами.

2024-12-25 12:52 UTC, Rzr18 commented
Выделил мобильное приложение, указал протоколы, переделал взаимодействие сервисов (очередь только для телеметрии), добавил состояние устройства, поправил домена

2024-12-25 13:01 UTC, closed without merging